---
# PCFly Config File:
fly_command.off: "&cFly disabled!" # Use &{Color_Index[12345678... etc]} to color!
fly_command.on: "&aFly enabled"
fly_eventHit_disabled: "&cNo Fly in PvP!"
fly_disabled_onjoin: "&dYour fly was disabled since you joined"
...
